baseURL = "https://pdabholkar.github.io/"
languageCode = "en-us"
title = "100 Days"
theme = "mainroad"
#disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
publishDir = "pdabholkar.github.io"

[params]
    author = "Prashant Dabholkar"
    description = "100 days of experiments with ML and FPGAs"
    githubUsername = "#"
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

## [[menu.main]]
##     url = "/project/"
##     name = "Projects"
##     weight = 3
## 
## # Social icons to be shown on the right-hand side of the navigation bar
## # The "name" field should match the name of the icon to be used
## # The list of available icons can be found at http://fontawesome.io/icons/
## 
## [[menu.icon]]
##     url = "mailto:me@example.com"
##     name = "envelope-o"
##     weight = 1
## 
## [[menu.icon]]
##     url = "https://github.com/username/"
##     name = "github"
##     weight = 2
## 
[[menu.icon]]
    url = "https://twitter.com/prashantpd/"
    name = "twitter"
    weight = 3

## [[menu.icon]]
##     url = "https://www.linkedin.com/in/username/"
##     name = "linkedin"
##     weight = 4
## 
## [[menu.icon]]
##     url = "https://www.stackoverflow.com/username/"
##     name = "stack-overflow"
##     weight = 5
